# Generated by Django 4.2.18 on 2025-04-12 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PL', 'Placed'), ('PR', 'Processing'), ('SH', 'Shipped'), ('DV', 'Delivered'), ('CM', 'Completed')], default='PL', max_length=2),
        ),
    ]
