# Generated by Django 4.2.18 on 2025-02-28 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_order_address_alter_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shippingCost',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='subtotalCost',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='taxCost',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='totalCost',
            field=models.IntegerField(default=0),
        ),
    ]
