# Generated by Django 4.2.18 on 2025-02-28 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_shippingcost_alter_order_subtotalcost_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='user',
        ),
    ]
