# Generated by Django 4.2.18 on 2025-03-05 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='address',
        ),
    ]
