# Generated by Django 4.2.18 on 2025-02-26 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_cartitem_user_alter_order_address_and_more'),
        ('products', '0005_alter_design_user_alter_designedproduct_user'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
