# Generated by Django 4.2.18 on 2025-02-12 01:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Design',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.URLField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
            options={
                'verbose_name': 'Design',
                'verbose_name_plural': 'Designs',
            },
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=254)),
            ],
            options={
                'verbose_name': 'ProductType',
                'verbose_name_plural': 'ProductTypes',
            },
        ),
        migrations.CreateModel(
            name='ProductTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=10)),
                ('pricePerUnit', models.IntegerField()),
                ('attributes', models.JSONField()),
                ('imageURL', models.URLField()),
                ('printableHeight', models.IntegerField()),
                ('printableWidth', models.IntegerField()),
                ('productType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.producttype')),
            ],
            options={
                'verbose_name': 'ProductTemplate',
                'verbose_name_plural': 'ProductTemplates',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designWidth', models.IntegerField()),
                ('designHeight', models.IntegerField()),
                ('designPosX', models.IntegerField()),
                ('designPosY', models.IntegerField()),
                ('design', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.design')),
                ('productTemplate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.producttemplate')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
    ]
