# Generated by Django 4.2.18 on 2025-04-13 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageURL', models.URLField()),
                ('start_x', models.IntegerField()),
                ('start_y', models.IntegerField()),
                ('end_x', models.IntegerField()),
                ('end_y', models.IntegerField()),
            ],
        ),
    ]
