# Generated by Django 4.2.18 on 2025-02-15 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_size_printableheight_size_printablewidth'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(default='TODO DESC'),
            preserve_default=False,
        ),
    ]
