# Generated by Django 4.2.18 on 2025-04-13 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_productimage_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='imageURL',
        ),
    ]
