# Generated by Django 4.2.18 on 2025-02-24 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='design',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
