# Generated by Django 4.2.18 on 2025-04-22 20:01

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_product_imageurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(default=products.models.create_sku, max_length=4, primary_key=True, serialize=False),
        ),
    ]
