# Generated by Django 4.2.18 on 2025-03-19 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_design_user_alter_designedproduct_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DesignedProduct',
        ),
    ]
