# Generated by Django 4.2.18 on 2025-04-29 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_productimage_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='imageURL',
        ),
    ]
