# Generated by Django 4.2.18 on 2025-04-29 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_remove_productimage_imageurl'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPreview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.color')),
                ('design', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.design')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
            options={
                'verbose_name': 'Produt Preview',
                'verbose_name_plural': 'Product Previews',
            },
        ),
    ]
