# Generated by Django 4.2.18 on 2025-04-29 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_productpreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpreview',
            name='image',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
