# Generated by Django 4.2.18 on 2025-05-01 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_productimage_color_mask_productimage_texture_mask'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.color')),
                ('productImage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productimage')),
            ],
        ),
    ]
