# Generated by Django 4.2.18 on 2025-05-05 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_productcolor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='color_mask',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='texture_mask',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
