# Generated by Django 4.2.18 on 2025-05-05 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_product_stock'),
        ('products', '0013_alter_productimage_color_mask_and_more'),
    ]

    operations = [
    ]
