# Generated by Django 4.2.18 on 2025-05-05 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_contactmessage_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
