# Generated by Django 4.2.18 on 2025-03-05 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderClaim',
        ),
    ]
